export const LOAD_KEYS = "LOAD_KEYS"
export const LOAD_PARAMS = "LOAD_PARAMS"
export const SET_PARAMS = "SET_PARAMS"
export const SET_URL_PARAMS = "SET_URL_PARAMS"
export const UPDATE_URL = "UPDATE_URL"